config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index';
  
  get '/home' => 'home#index'
  
    get '/cache' => 'shop#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron well col-md-10 row col-md-offset-1 text-center">
<h1>Yee</h1>
<p>This is a random placeholder paragraph. Here will be blog posts I assume???</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Call to Battle</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
     <script type="text/javascript" language="JavaScript">
      function set_logo_size()
      {
          //var window_width = $(window).width();
          //$('.logo-pic').attr('style', 'width:' + window_width - 120 + 'px;');
        /*  if($(this).scrollTop() < 100) {
           $('.padnav').css('padding-top', $('div .logo-pic').css('height'))
          } else {*/
            $('.padnav').css('padding-top', 0)
          //}
          
      }
      $(document).ready(function() {
          set_logo_size();
          $(window).bind('resize', function() { set_logo_size(); });
      });
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
   <!-- <div class="col-md-12 logo-pic">
    </div>-->

            
    <div class='padnav'>
     <nav class="navbar navbar-default main-nav" role="navigation">
      <div class='container'>
        
               
            
      <div class="navbar-brand logo-pic">
           <a href=home><%= image_tag "logo.png", :class => "logo-pic"%></a>
        </div>
        <!--<div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to root_path, class: 'navbar-brand navtext' do %>
              Home
            <% end %>
            </div>-->
            
            
            
             <div class="collapse navbar-collapse" id="main-nav-collapse">
              <ul class="nav navbar-nav navbar-left navtext">
                <li><%= link_to "Features", home_path  %></li>
                
                <li class="skin"><%= link_to "Weapon Cache", cache_path  %></li>
              </ul>
              
                            <ul class="nav navbar-nav navbar-right navtext">
                <li><%= link_to "Plans", home_path  %></li>
                <li><%= link_to "Other Mods", home_path %></li>
               </ul>
            </div>
            
           
      </div>
    </nav>
    </div>
<div class="main">
  <%= yield %>
</div>

</body>
</html>

app/views/shop/index.html.erb
<html>
    <head>
  <title="Weapons Cache"/>
        <%= stylesheet_link_tag 'shop', media: 'all', 'data-turbolinks-track' =>true  %>
    </head>
    <body>
       <div class="jumbotron well col-md-10 row col-md-offset-1 text-center">
        <h1>Welcome to the weapons cache!</h1>
        <p>This is a random placeholder paragraph.</p>
        </div>
        
        <div class="jumbotron col-md-3 row col-md-offset-1 crate woodcrate"><img src="assets/crates/weaponcrate.png" class="crpic">
            <div class="well descwell">
                <h1 class="text-center dhead">Wooden Crate</h1>
                <p class="text-center desc">A wooden crate can contain a <span style="color:#fff9d3;">Common</span>, 
                <span style="color:#bffc8a;">Exceptional</span>, or <span style="color: #00e1ff;">Magneficant</span> Skin</p>
            </div>
            
             <div class="well buywell">
                    <p class="text-center">Buy $0.99</p>
                </div>
        </div>
        
        <div class="jumbotron col-md-3 row col-md-offset-1 crate ironcrate"><img src="assets/crates/ironcrate.png" class="crpic">
            <div class="well descwell">
                <h1 class="text-center dhead" style="color: #e3e4e5 !important;">Iron Crate</h1>
                <p class="text-center desc">An iron crate can contain either an <span style="color:#bffc8a;">Exceptional</span> or a <span style="color: #00e1ff;">Magneficant</span> Skin!</p>
            </div>
            
             <div class="well buywell">
                    <p class="text-center">Buy $2.49</p>
                </div>
        </div>
         
         
         <div class="jumbotron col-md-3 row col-md-offset-1 crate steelcrate"><img src="assets/crates/steelcrate.png" class="crpic">
            <div class="well descwell" style="padding-bottom: 30px">
                <h1 class="text-center dhead" style="color: #8ebaff !important;">Steel Crate</h1>
                <p class="text-center desc">A steel crate will always contain a <span style="color: #00e1ff;">Magneficant</span> Skin!</p>
                </br>
            </div>
              <div class="well buywell">
                    <p class="text-center">Buy $3.99</p>
                </div>
        </div>
    </body>
</html>